# Site settings
title: teddyzhang29
header-img: img/header/index.jpg
email: teddyzhang29@gmail.com
description: "有意瞄准，无意击发"
baseurl: ""
url: ""
github_username:  teddyzhang29
port: 4000
# Build settings
markdown: kramdown
highlighter: rouge
#pygments
permalink: /:title
gems: [jekyll-paginate]
paginate_path: "page:num"
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: b01b25ef485fb33917b9                            #生成的clientID
  clientSecret: 7737058900ddef0b581020bf5d057e9d39266091    #生成的clientSecret
  repo: teddyzhang29.github.io    #仓库名称
  owner: teddyzhang29    #github用户名
  admin: teddyzhang29
  distractionFreeMode: false #是否启用类似FB的阴影遮罩

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# 统计
# Google Analytics
ga_track_id: 'UA-137049499-1'            # Format: UA-xxxxxx-xx
ga_domain: auto                          # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto